### Criar orfanato
POST http://localhost:3333/orphanages
content-type: multipart/form-data

{
  "name": "Criançada do gino",
  "latitude": -23.4712267,
  "longitude": -47.7320529,
  "about": "Sobre o orfanato",
  "instructions": "Venha visitar",
  "opening_hours": "Das 8h até 18h",
  "open_on_weekends": true
}

### Listar orfanatos
GET http://localhost:3333/orphanages

### Mostrar orfanato
GET http://localhost:3333/orphanages/2